### ISSUE TITLE
TypeError: Cannot read property 'expressJwtSecret' of undefined

### ISSUE THREAD

**Issue by ptomaszi** [auth0/node-jwks-rsa#124]
### Description

When using TypeScript to build NodeJs based API with Auth0 authentication enabled, I get the following Type error when executing the "ts-node" compiler:

```
import jwt from "express-jwt";
import jwksRsa from "jwks-rsa";

const checkJwt = jwt({
  secret: jwksRsa.expressJwtSecret({
    cache: true,
    rateLimit: true,
    jwksRequestsPerMinute: 5,
    jwksUri: `https://xxxxxxxxx.eu.auth0.com/.well-known/jwks.json`
  }),
  audience: "https://xxxx-node-api",
  issuer: `https://xxxxxxxxxxxx.eu.auth0.com/`,
  algorithms: ["RS256"]
});
export default checkJwt;
```

**`E:\Projects\express-ads-api\src\middleware\auth.js:6
    secret: jwks_rsa_1["default"].expressJwtSecret({
                                  ^
TypeError: Cannot read property 'expressJwtSecret' of undefined
    at Object.<anonymous> (E:\Projects\express-ads-api\src\middleware\auth.js:6:35)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (E:\Projects\express-ads-api\src\routes\company.js:41:14)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)`**

### Environment

> Please provide the following:

- **Version of this library used:** "jwks-rsa": "^1.6.2",
- **Version of the platform or framework used, if applicable:** "ts-node": "^8.6.2", "typescript": "^3.7.5"
- **Other relevant versions (language, server software, OS, browser):** "express": "^4.17.1",
- **Other modules/plugins/libraries that might be involved:**

**Comment by rojasc** [comment]
I'm running into the same issue. Have you had any luck working around this?

**Comment by ptomaszi** [comment]
I had to change how I import my dependecies to:

import { expressJwtSecret } from "jwks-rsa";
import jwt = require("express-jwt");

This is now working.
