### ISSUE TITLE
Error in node_modules/jwks-rsa/node_modules/lru-memoizer/index.js:18 

### ISSUE THREAD

**Issue by viditsaxena** [auth0/node-jwks-rsa#18]
I am using Node as backend and was wiring it up with RS256 spec. Installed all the packages mentioned here https://auth0.com/docs/quickstart/backend/nodejs

When I start my server I get below error from one of the libraries. It's sourcing from here, jwks-rsa/node_modules/lru-memoizer/index.js:18 

`  _.extend(load, { del }, options);
                           ^
SyntaxError: Unexpected token }
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/viditsaxena/Documents/unwander/unwander-services/node_modules/jwks-rsa/lib/wrappers/cache.js:45:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/viditsaxena/Documents/unwander/unwander-services/node_modules/jwks-rsa/lib/wrappers/index.js:8:14)
    at Module._compile (module.js:460:26)`

**Comment by MedSolve** [comment]
I have the same issue did it work by updating to *"lru-memoizer": "^1.11.1"* ?

**Comment by vsaxena-mdsol** [comment]
Turns out my node version on the computer was outdated. I had to upgrade to 5.12 for it to work.

**Comment by viditsaxena** [comment]
It worked after upgraded my local node version. Was using a very old one.

**Comment by nhammond101** [comment]
Ran into this issue when using `jwks-rsa` in older browsers (ie11 🤦🏻‍♂️).  The shorthand property `{ del }` in the expand function causes the issue, as the browsers don't support shorthand that was introduced in es2015 spec.  I've submitted a [PR](https://github.com/jfromaniello/lru-memoizer/pull/9) to that repo to _expand_ the property.
