### ISSUE TITLE
handleSigningKeyError is being ignored

### ISSUE THREAD

**Issue by hbarcelos** [auth0/node-jwks-rsa#33]
Here's my code:

```javascript
jwks.expressJwtSecret({
    cache: true,
    rateLimit: true,
    jwksRequestsPerMinute: 5,
    jwksUri: '<my URI>',
    handleSigningKeyError: (err, cb) => {
      console.log('>>>>>>>>>>>>>', err)
      return cb(new Error('Authentication Error'));
    },
  })
```

The `handleSigningKeyError` is not being called.

When I call the API with an invalid token, it gives back:

```
UnauthorizedError: secret or public key must be provided
    at /home/henrique/labs/auth0/playground/node_modules/express-jwt/lib/index.js:102:22
    at /home/henrique/labs/auth0/playground/node_modules/jsonwebtoken/verify.js:27:18
    at process._tickCallback (internal/process/next_tick.js:150:11)
```

**Comment by Levino** [comment]
What did you expect should happen? Why don't you make a PR and add a test that reproduces your bug?

**Comment by djom20** [comment]
I have the UnauthorizedError issue right now, I can't solve it. Did you find any solution for that @hbarcelos ?

**Comment by ChakirMrabet** [comment]
I also have this issue.
