### ISSUE TITLE
TypeError: Object [object Object] has no method 'find'

### ISSUE THREAD

**Issue by Sebosek** [auth0/node-jwks-rsa#4]
Hi guys,

I found bug. Here is snippet how, I'm using jwks-rsa package with log added bellow.

```typescript
const jwtMiddleware = require("express-jwt");
const jwksRsa = require("jwks-rsa");
const router = Router();

export class Notification {
    router: any;

    constructor(private env: any) {
        this.router = router.use(jwtMiddleware({
            secret: jwksRsa.expressJwtSecret({
                strictSsl: false,
                jwksUri: env.JSON_WEB_KEY_SET
            })
        }));

        /**
         * @swagger
         * /notifications:
         *   post:
         *     tags:
         *       - Notifications
         *     description: Creates new nofication thru Socket.io
         *     produces:
         *       - application/json
         *     responses:
         *       200:
         *         description: Success status code
         *     parameters:
         *       - name: notify
         *         in: body
         *         description: Notify definition
         *         required: true
         *         schema:
         *           $ref: '#/definitions/Notify'
         *       - name: authorization
         *         in: header
         *         type: string
         *         required: true
         *         default: 'Bearer '
         *         description: 'Usage: Bearer xxx'
         */
        this.router = router.post("/", (req: ShRequest, res: Response) => {
            const notify = <Notify>req.body;

            // ... code lives here

            res.sendStatus(200);
        });
    }
};
```

```
TypeError: Object [object Object] has no method 'find'
    at /usr/lib/realtime_notifications/node_modules/jwks-rsa/lib/JwksClient.js:54:24
    at /usr/lib/realtime_notifications/node_modules/jwks-rsa/lib/JwksClient.js:126:16
    at Request._callback (/usr/lib/realtime_notifications/node_modules/jwks-rsa/lib/JwksClient.js:94:16)
    at Request.self.callback (/usr/lib/realtime_notifications/node_modules/request/request.js:187:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/usr/lib/realtime_notifications/node_modules/request/request.js:1048:10)
    at Request.emit (events.js:95:17)
    at IncomingMessage.<anonymous> (/usr/lib/realtime_notifications/node_modules/request/request.js:969:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:929:16
```

**Comment by sdd** [comment]
The response body from `request` must be a POJO since `opts.json`=`true` for request.

`res.body.keys` must be an array, since `.filter` and `.map` are called successfully, but the call to `.find` fails. 

`Array.find` is not present on NodeJS < v4. There's your problem - you are using a very old version of node, probably 0.10 or 0.12.
