### ISSUE TITLE
Getting jwks Failure: Error: SSL Error: SELF_SIGNED_CERT_IN_CHAIN

### ISSUE THREAD

**Issue by barathank** [auth0/node-jwks-rsa#67]
When trying to get the JWT keys to validate a token, the request fails when the environment has a self-signed cert in the chain behind enterprise proxy. 
jwks Fetching keys from 'https://authserver/oauth2/default/v1/keys' +0ms
  jwks Failure: Error: SSL Error: SELF_SIGNED_CERT_IN_CHAIN
    at Request.onRequestResponse (node_modules/request/request.js:952:24)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:551:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)
    at TLSSocket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11) +181ms
Error: SSL Error: SELF_SIGNED_CERT_IN_CHAIN
    at Request.onRequestResponse (node_modules/request/request.js:952:24)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:551:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)
    at TLSSocket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)

**Comment by sonman1** [comment]
Have seen the same issue. No new insights or debug - same as noted here. Has anyone discovered a work around?

**Comment by jajaperson** [comment]
Me too 😢

**Comment by cconcannon** [comment]
I just opened a PR which will allow resolution of this issue by allowing pass-through of (among other things) a private certificate authority chain via the request options _agentOptions_  property to the request library configuration

https://github.com/auth0/node-jwks-rsa/pull/84
