### ISSUE TITLE
Missing "use":"sig" in some provider's webkey causing JwksError: The JWKS endpoint did not contain any signing keys

### ISSUE THREAD

**Issue by lyxhaven** [auth0/node-jwks-rsa#70]
I encountered a provider (`OneLogin`) that did not specify "use":"sig" for their webkey.

This will cause the jwksClient to crash:
```
JwksError: The JWKS endpoint did not contain any signing keys
    at /home/runner/node_modules/jwks-rsa/lib/JwksClient.js:122:21
    at Request._callback (/home/runner/node_modules/jwks-rsa/lib/JwksClient.js:94:16)
    at Request.self.callback (/home/runner/node_modules/request/request.js:185:22)
    at Request.emit (events.js:180:13)
    at Request.<anonymous> (/home/runner/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:180:13)
    at IncomingMessage.<anonymous> (/home/runner/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:272:13)
    at IncomingMessage.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1106:12)
  name: 'JwksError',
  message: 'The JWKS endpoint did not contain any signing keys' }
undefined
Process crashed with: TypeError: Cannot read property 'publicKey' of undefined
    at client.getSigningKey (evalmachine.<anonymous>:15:28)
    at /home/runner/node_modules/jwks-rsa/lib/JwksClient.js:51:18
    at /home/runner/node_modules/jwks-rsa/lib/JwksClient.js:122:18
    at Request._callback (/home/runner/node_modules/jwks-rsa/lib/JwksClient.js:94:16)
    at Request.self.callback (/home/runner/node_modules/request/request.js:185:22)
    at Request.emit (events.js:180:13)
    at Request.<anonymous> (/home/runner/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:180:13)
    at IncomingMessage.<anonymous> (/home/runner/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:272:13)
```

I think this PR in another library solves a similar problem: https://github.com/IdentityModel/IdentityModel.OidcClient2/pull/77
Also a similar issue in the above library that raised by another user: https://github.com/IdentityModel/IdentityModel.OidcClient2/issues/65

And after taking a glance at the client code, I think here might be the place for improvement/enhancement: https://github.com/auth0/node-jwks-rsa/blob/master/src/JwksClient.js#L52
We could change this line from:
```
.filter(key => key.use === 'sig' && key.kty === 'RSA' && key.kid && ((key.x5c && key.x5c.length) || (key.n && key.e)))
```
to:
```
.filter(key => (key.use === 'sig' || key.use === null) && key.kty === 'RSA' && key.kid && ((key.x5c && key.x5c.length) || (key.n && key.e)))
```

Thanks for looking and helping in advance !

**Comment by lyxhaven** [comment]
I created a PR here for this issue: https://github.com/auth0/node-jwks-rsa/pull/71

**Comment by krumware** [comment]
We also need this

**Comment by hawryschuk-quest** [comment]
We need this too

**Comment by kkuzmina** [comment]
Any update on this?
